### ISSUE TITLE
Deployment on BeeHive

### ISSUE THREAD

**Issue by dcoraboeuf** [dcoraboeuf/myconfig#61]
- needs a zero-file configuration for the 'prod' profile
- cloudbee XML configuration file in WEB-INF
  - declares a spring active profile for prod as a system property
  - declares the JNDI resource using myconfig.jdbc.url, myconfig.jdbc.user & myconfig.jdbc.password
- the web.xml must refer to this datasource (1)

(1) this could be a problem for 'dev' and other test profiles

**Comment by dcoraboeuf** [comment]
- CB configuration file: http://wiki.cloudbees.com/bin/view/RUN/CloudBeesWebXml
- CB configuration parameters: http://wiki.cloudbees.com/bin/view/RUN/Configuration+Parameters

**Comment by dcoraboeuf** [comment]
Error on startup after deployment of 0.0.1-17:

```
org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'CB!gu1nness'
    at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1452)
    at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
    at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
    at net.sf.dbinit.DBInit.getConnection(DBInit.java:396)
    at net.sf.dbinit.DBInit.run(DBInit.java:555)
```
